apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: team-d-cmpt756s4
  labels:
    app: team-d-cmpt756s4
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - c756ns
  selector:
    matchLabels:
      app: team-d-cmpt756s4
  endpoints:
  - port: http
    path: /metrics
